baseURL      = "https://demo.stack.jimmycai.com/"
languageCode = "zh-cn"
title        = "Hugo Theme Stack"
theme = "hugo-theme-stack"

# Theme i18n support
# See i18n folder for available languages
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is a CJK language
# This will make .Summary and .WordCount behave correctly
hasCJKLanguage = true



[pagination]
    pagerSize = 5

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = "hugo-theme-stack"
