[en]
    languageName = "English"
    title        = "vobl"
    weight       = 2
    [en.params.sidebar]
        subtitle = "Welcome to my blog"

[zh]
    languageName = "简体中文"
    title        = "vobl"
    weight       = 1
    [zh.params.sidebar]
        subtitle = ""

[zh-hant-tw]
    languageName = "繁體中文"
    title        = "vobl"
    weight       = 3
    [zh-hant-tw.params.sidebar]
        subtitle = "欢迎来到我的博客"

[ja]
    languageName = "日本語"
    title        = "vobl"
    weight       = 4
    [ja.params.sidebar]
        subtitle = "Welcome to my blog"
