[[social]]
    identifier = "抖音"
    name       = "抖音"
    url        = "https://www.douyin.com/user/MS4wLjABAAAAIHl26glyy12oz6SXxRDgL4Bh18y6Z3jBdQO5FcVzWTM?from_tab_name=main"
    [social.params]
        icon = "brand-tiktok"

[[social]]
    identifier = "bilibili"
    name       = "Bilibili"
    url        = "https://space.bilibili.com/1271779116"
    [social.params]
        icon = "brand-bilibili"
