mainSections   = ["post"]
rssFullContent = true
favicon        = "icons/907.svg"

[footer]
    since = 2025

[sidebar]
    emoji    = "ğŸ˜Š"
    subtitle = "æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººåšå®¢"
    avatar   = "img/icon.png"

[article]
    [article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[comments]
    # See complete configuration in config/_default/params.toml
    enabled  = true
    provider = "disqus"
